"""DataMixin

Revision ID: aa46af9be5fe
Revises: 2ecddfe6bad2
Create Date: 2024-04-04 21:34:55.755804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa46af9be5fe'
down_revision: Union[str, None] = '2ecddfe6bad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('dta_cadastro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('usuarios', sa.Column('dta_atualizado', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'dta_atualizado')
    op.drop_column('usuarios', 'dta_cadastro')
    # ### end Alembic commands ###
